/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipoIndexRouteImport } from './routes/equipo.index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as EquipoDisponibilidadRouteImport } from './routes/equipo.disponibilidad'
import { Route as EquipoEquipmentIdRouteImport } from './routes/equipo.$equipmentId'
import { Route as ConfigurationTeamRouteImport } from './routes/configuration/team'
import { Route as ClienteCarritoRouteImport } from './routes/cliente.carrito'
import { Route as ClienteEquipoEquipmentIdRouteImport } from './routes/cliente.equipo.$equipmentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoIndexRoute = EquipoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipoRoute,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const EquipoDisponibilidadRoute = EquipoDisponibilidadRouteImport.update({
  id: '/disponibilidad',
  path: '/disponibilidad',
  getParentRoute: () => EquipoRoute,
} as any)
const EquipoEquipmentIdRoute = EquipoEquipmentIdRouteImport.update({
  id: '/$equipmentId',
  path: '/$equipmentId',
  getParentRoute: () => EquipoRoute,
} as any)
const ConfigurationTeamRoute = ConfigurationTeamRouteImport.update({
  id: '/configuration/team',
  path: '/configuration/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteCarritoRoute = ClienteCarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => ClienteRoute,
} as any)
const ClienteEquipoEquipmentIdRoute =
  ClienteEquipoEquipmentIdRouteImport.update({
    id: '/equipo/$equipmentId',
    path: '/equipo/$equipmentId',
    getParentRoute: () => ClienteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/equipo': typeof EquipoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventario': typeof InventarioRoute
  '/signup': typeof SignupRoute
  '/cliente/carrito': typeof ClienteCarritoRoute
  '/configuration/team': typeof ConfigurationTeamRoute
  '/equipo/$equipmentId': typeof EquipoEquipmentIdRoute
  '/equipo/disponibilidad': typeof EquipoDisponibilidadRoute
  '/cliente/': typeof ClienteIndexRoute
  '/equipo/': typeof EquipoIndexRoute
  '/cliente/equipo/$equipmentId': typeof ClienteEquipoEquipmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventario': typeof InventarioRoute
  '/signup': typeof SignupRoute
  '/cliente/carrito': typeof ClienteCarritoRoute
  '/configuration/team': typeof ConfigurationTeamRoute
  '/equipo/$equipmentId': typeof EquipoEquipmentIdRoute
  '/equipo/disponibilidad': typeof EquipoDisponibilidadRoute
  '/cliente': typeof ClienteIndexRoute
  '/equipo': typeof EquipoIndexRoute
  '/cliente/equipo/$equipmentId': typeof ClienteEquipoEquipmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/equipo': typeof EquipoRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventario': typeof InventarioRoute
  '/signup': typeof SignupRoute
  '/cliente/carrito': typeof ClienteCarritoRoute
  '/configuration/team': typeof ConfigurationTeamRoute
  '/equipo/$equipmentId': typeof EquipoEquipmentIdRoute
  '/equipo/disponibilidad': typeof EquipoDisponibilidadRoute
  '/cliente/': typeof ClienteIndexRoute
  '/equipo/': typeof EquipoIndexRoute
  '/cliente/equipo/$equipmentId': typeof ClienteEquipoEquipmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/cliente'
    | '/clientes'
    | '/dashboard'
    | '/equipo'
    | '/forgot-password'
    | '/inventario'
    | '/signup'
    | '/cliente/carrito'
    | '/configuration/team'
    | '/equipo/$equipmentId'
    | '/equipo/disponibilidad'
    | '/cliente/'
    | '/equipo/'
    | '/cliente/equipo/$equipmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/clientes'
    | '/dashboard'
    | '/forgot-password'
    | '/inventario'
    | '/signup'
    | '/cliente/carrito'
    | '/configuration/team'
    | '/equipo/$equipmentId'
    | '/equipo/disponibilidad'
    | '/cliente'
    | '/equipo'
    | '/cliente/equipo/$equipmentId'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/cliente'
    | '/clientes'
    | '/dashboard'
    | '/equipo'
    | '/forgot-password'
    | '/inventario'
    | '/signup'
    | '/cliente/carrito'
    | '/configuration/team'
    | '/equipo/$equipmentId'
    | '/equipo/disponibilidad'
    | '/cliente/'
    | '/equipo/'
    | '/cliente/equipo/$equipmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  ClientesRoute: typeof ClientesRoute
  DashboardRoute: typeof DashboardRoute
  EquipoRoute: typeof EquipoRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventarioRoute: typeof InventarioRoute
  SignupRoute: typeof SignupRoute
  ConfigurationTeamRoute: typeof ConfigurationTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/': {
      id: '/equipo/'
      path: '/'
      fullPath: '/equipo/'
      preLoaderRoute: typeof EquipoIndexRouteImport
      parentRoute: typeof EquipoRoute
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/equipo/disponibilidad': {
      id: '/equipo/disponibilidad'
      path: '/disponibilidad'
      fullPath: '/equipo/disponibilidad'
      preLoaderRoute: typeof EquipoDisponibilidadRouteImport
      parentRoute: typeof EquipoRoute
    }
    '/equipo/$equipmentId': {
      id: '/equipo/$equipmentId'
      path: '/$equipmentId'
      fullPath: '/equipo/$equipmentId'
      preLoaderRoute: typeof EquipoEquipmentIdRouteImport
      parentRoute: typeof EquipoRoute
    }
    '/configuration/team': {
      id: '/configuration/team'
      path: '/configuration/team'
      fullPath: '/configuration/team'
      preLoaderRoute: typeof ConfigurationTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/carrito': {
      id: '/cliente/carrito'
      path: '/carrito'
      fullPath: '/cliente/carrito'
      preLoaderRoute: typeof ClienteCarritoRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/cliente/equipo/$equipmentId': {
      id: '/cliente/equipo/$equipmentId'
      path: '/equipo/$equipmentId'
      fullPath: '/cliente/equipo/$equipmentId'
      preLoaderRoute: typeof ClienteEquipoEquipmentIdRouteImport
      parentRoute: typeof ClienteRoute
    }
  }
}

interface ClienteRouteChildren {
  ClienteCarritoRoute: typeof ClienteCarritoRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
  ClienteEquipoEquipmentIdRoute: typeof ClienteEquipoEquipmentIdRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteCarritoRoute: ClienteCarritoRoute,
  ClienteIndexRoute: ClienteIndexRoute,
  ClienteEquipoEquipmentIdRoute: ClienteEquipoEquipmentIdRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

interface EquipoRouteChildren {
  EquipoEquipmentIdRoute: typeof EquipoEquipmentIdRoute
  EquipoDisponibilidadRoute: typeof EquipoDisponibilidadRoute
  EquipoIndexRoute: typeof EquipoIndexRoute
}

const EquipoRouteChildren: EquipoRouteChildren = {
  EquipoEquipmentIdRoute: EquipoEquipmentIdRoute,
  EquipoDisponibilidadRoute: EquipoDisponibilidadRoute,
  EquipoIndexRoute: EquipoIndexRoute,
}

const EquipoRouteWithChildren =
  EquipoRoute._addFileChildren(EquipoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  ClienteRoute: ClienteRouteWithChildren,
  ClientesRoute: ClientesRoute,
  DashboardRoute: DashboardRoute,
  EquipoRoute: EquipoRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventarioRoute: InventarioRoute,
  SignupRoute: SignupRoute,
  ConfigurationTeamRoute: ConfigurationTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
