/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigurationTeamRouteImport } from './routes/configuration/team'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationTeamRoute = ConfigurationTeamRouteImport.update({
  id: '/configuration/team',
  path: '/configuration/team',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/equipo': typeof EquipoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventario': typeof InventarioRoute
  '/signup': typeof SignupRoute
  '/configuration/team': typeof ConfigurationTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/equipo': typeof EquipoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventario': typeof InventarioRoute
  '/signup': typeof SignupRoute
  '/configuration/team': typeof ConfigurationTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/equipo': typeof EquipoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inventario': typeof InventarioRoute
  '/signup': typeof SignupRoute
  '/configuration/team': typeof ConfigurationTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/clientes'
    | '/dashboard'
    | '/equipo'
    | '/forgot-password'
    | '/inventario'
    | '/signup'
    | '/configuration/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/clientes'
    | '/dashboard'
    | '/equipo'
    | '/forgot-password'
    | '/inventario'
    | '/signup'
    | '/configuration/team'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/clientes'
    | '/dashboard'
    | '/equipo'
    | '/forgot-password'
    | '/inventario'
    | '/signup'
    | '/configuration/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  ClientesRoute: typeof ClientesRoute
  DashboardRoute: typeof DashboardRoute
  EquipoRoute: typeof EquipoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InventarioRoute: typeof InventarioRoute
  SignupRoute: typeof SignupRoute
  ConfigurationTeamRoute: typeof ConfigurationTeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuration/team': {
      id: '/configuration/team'
      path: '/configuration/team'
      fullPath: '/configuration/team'
      preLoaderRoute: typeof ConfigurationTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  ClientesRoute: ClientesRoute,
  DashboardRoute: DashboardRoute,
  EquipoRoute: EquipoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InventarioRoute: InventarioRoute,
  SignupRoute: SignupRoute,
  ConfigurationTeamRoute: ConfigurationTeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
